# Generated by Django 5.1.4 on 2024-12-27 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_remove_user_model_followers_followers_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Followers',
            new_name='Follower',
        ),
    ]
