# Generated by Django 5.1.4 on 2024-12-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rename_followers_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
