# Generated by Django 5.1.4 on 2025-01-10 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='follower_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/'),
        ),
    ]
